name: jkmapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.0.15
  image_picker:  ^1.1.2
  file_picker: ^5.0.0
  dio: ^5.0.0 # 使用最新版本
  dio_cookie_manager: ^3.1.1  # 用於管理 Cookies
  cookie_jar: ^4.0.8  # 用於儲存 Cookies
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Kapakana
      fonts:
        - asset: assets/fonts/Kapakana[wght].ttf
          weight: 700
